/*****************************************************************************

		Copyright (c) My Company

 Project:  LR_2_Andreeva_6313
 FileName: LR_2_ANDREEVA_6313.INC
 Purpose:  Project's global declarations
 Written by: Visual Prolog
 Comments:
*****************************************************************************/


/*****************************************************************************
			User's Declarations
*****************************************************************************/
global domains
  DB_SELECTOR = browselist_db	% For treebrowser tool
  FILE = fileselector1; fileselector2 % To be edited
